export const siteConfig = {
  title: 'Music Widgets Components',
  description: 'Colección de widgets minimalistas pensados para el diseño de interfaces musicales. Ofrece recursos reutilizables con soporte para temas claro y oscuro, ideales para crear experiencias modernas y accesibles.',
  keywords: [
    'widgets',
    'components',
    'astro',
    'HTML',
    'CSS',
    'JavaScript',
    'tailwind',
    'web development',
    'UI components',
    'reusable components',
    'minimalist design',
    'dark mode',
    'light mode',
    'responsive design',
    'frontend development',
    'web design',
    'user interface',
    'web components',
    'frankuxui',
    'music',
    'music app',
    'music player',
    'audio player',
    'UI',
    'UX',
    'user experience',
    'web widgets',
    'web components library',
    'modern design',
  ],
  author: {
    name: 'Frank Esteban',
    alternateName: 'FrankUXUI',
  },
  ogImage: '/og.jpg',
  logo: '/frankuxui_frontend_developer_ux_ui_designer_logo.png',
  social: {
    github: 'https://github.com/frankuxui',
    linkedin: 'https://www.linkedin.com/in/frankuxui',
    figma: 'https://www.figma.com/@frankuxui',
    codepen: 'https://codepen.io/frankuxui',
    codesandbox: 'https://codesandbox.io/u/frankuxui',
    instagram: 'https://instagram.com/frankuxui',
    dribbble: 'https://dribbble.com/frankuxui',
    tailwindComponents: 'https://www.creative-tim.com/twcomponents/u/frankuxui',
    devto: 'https://dev.to/frankuxui',
  }
}